# Artax: personal laptop.
#
# Composition only. Everything reusable lives in `modules/`; the facts about
# this machine live in `hosts/artax.nix`.
{
  pkgs,
  ...
}:

{
  imports = [
    # Hardware scan. Generated by `nixos-generate-config`; do not edit by hand.
    ../../hosts/artax.nix
  ];

  # Brave, VS Code, Zoom, Spotify and Dropbox are all unfree.
  mkononenko.nix.allowUnfree = true;

  mkononenko.desktop = {
    enable = true;
    hostname = "artax";
    ntfs.enable = true;
  };

  mkononenko.user.mkononenko.enable = true;

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  environment.systemPackages = with pkgs; [
    git
    xclip
    wget
    unzip
    networkmanager
    blueman
    cachix
  ];

  system.stateVersion = "25.05";
}
